In [1]:
# Numpy in python 
# in python, everything is an object
# ex: v = 4 varible value = 4, func1,func2, ...

In [2]:
import sys
import numpy as np

In [3]:
# array in python
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
a = np.array([1,2,3,4])

In [5]:
a[0],a[1],a[3]

(1, 2, 4)

In [6]:
a[1:]# print ptu in array from index i

array([2, 3, 4])

In [7]:
b = [1,1.4,4,3,4,5,6,7,7.5,8,9,10,45,23]
b[2:3]
#c = [2,5,3,7,2,9,6,5,7,10,5,3,4]
#c[1:10] # print array element from index i to index k-1

[4]

In [8]:
c = [2,5,3,7,2,9,6,5,7,10,5,3,4]
c[0:-1] # print array element from index to index n-1-k

[2, 5, 3, 7, 2, 9, 6, 5, 7, 10, 5, 3]

In [9]:
c[1::2]# print array element, index =i+nk (k =0,1,2,...)

[5, 7, 9, 5, 10, 3]

In [10]:
c[1::-1]

[5, 2]

In [11]:
a[[-1,1,2]]# print element have index as this

array([4, 2, 3])

In [12]:
a.dtype# get type

dtype('int32')

In [13]:
np.array([1,2,3,4],dtype=np.int64)# ep kieu

array([1, 2, 3, 4], dtype=int64)

In [14]:
np.array([1,2,3,4],dtype=np.float)

C:\Users\PC\AppData\Local\Temp\ipykernel_7776\2214947681.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([1,2,3,4],dtype=np.float)


array([1., 2., 3., 4.])

In [15]:
A = np.array(
[
    [
        [1,2,3],
        [2,3,4]
    ],

    [
        [2,3,4],
        [3,4,5]
    ]
])

In [16]:
A.shape

(2, 2, 3)

In [17]:
A.ndim

3

In [18]:
A.size

12

In [19]:
A.dtype

dtype('int32')

In [20]:
a = np.array([1,2,3,4,5,6])
a.sum()

21

In [21]:
a.mean()

3.5

In [22]:
a.std()# tinh do lech chuan
#     sigma(a[i]-mean(a))^2
#sqrt------------------------
#              len(a)

1.707825127659933

In [23]:
a.var()# tinh phuong sai
#phuong sai = do lech chuan binh phuong

2.9166666666666665

In [24]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [25]:
A.sum(axis = -1)# tinh tong theo cot, hang

array([ 6, 15, 24])

In [26]:
d = np.arange(5,10)
d[:]

array([5, 6, 7, 8, 9])

In [27]:
e = (1,2,4,1,4,3)
print(e)

(1, 2, 4, 1, 4, 3)


In [28]:
type(e)

tuple

In [29]:
np.arange(0,1,1)#from 0 to n-k, moi so cach nhau k

array([0])

In [30]:
a = "manh"
print("ten toi la", {a})

ten toi la {'manh'}


In [31]:
#tạo một dữ liệu
import pandas as pd
mark = pd.Series([10,8,9,7.5,5.5,9.3,8.7,7,6,10,8])
mark

0     10.0
1      8.0
2      9.0
3      7.5
4      5.5
5      9.3
6      8.7
7      7.0
8      6.0
9     10.0
10     8.0
dtype: float64

In [32]:
mark.name = 'mark object'

In [33]:
mark

0     10.0
1      8.0
2      9.0
3      7.5
4      5.5
5      9.3
6      8.7
7      7.0
8      6.0
9     10.0
10     8.0
Name: mark object, dtype: float64

In [34]:
mark.index = ['Nam','Hai','Linh','Chien','Anh','Hue','Minh','Duc','Thang','Huy','Trang']

In [35]:
mark

Nam      10.0
Hai       8.0
Linh      9.0
Chien     7.5
Anh       5.5
Hue       9.3
Minh      8.7
Duc       7.0
Thang     6.0
Huy      10.0
Trang     8.0
Name: mark object, dtype: float64

In [36]:
len(mark)

11

In [37]:
data = pd.Series([1,2,3],[4,5,6])
#Series chỉ là kiểu dữ liệu một chiều

In [38]:
data

4    1
5    2
6    3
dtype: int64

In [39]:
data.index = ['one','two','three']

In [40]:
#Data frame là kiểu dữ liệu 2 chiều
import numpy as np
import pandas as pd


In [41]:
Population = [35.467,63.951,80.94,60.665,127.061,64.511,318.523]
GDP = [1785387,2833687,3874437,2167744,4602367,2950039,17348075]
Surface = [9984670,640679,357114,301336,377930,242495,9525067]
HDI = [0.913,0.888,0.916,0.873,0.891,0.907,0.915]
Cotinent = ['America','Europe','Europe','Europe','Asia','Europe','America']

In [42]:
G7 = {'Population': Population,'GDP': GDP,'Surface':Surface,'HDI':HDI,'Continent':Cotinent}

In [43]:
G7_Stats = pd.DataFrame(G7)
G7_Stats

Population       GDP  Surface    HDI Continent
0      35.467   1785387  9984670  0.913   America
1      63.951   2833687   640679  0.888    Europe
2      80.940   3874437   357114  0.916    Europe
3      60.665   2167744   301336  0.873    Europe
4     127.061   4602367   377930  0.891      Asia
5      64.511   2950039   242495  0.907    Europe
6     318.523  17348075  9525067  0.915   America

In [44]:
G7_Stats.index=['Canada','France','Germany','Italy','Japan','United Kingdom','United States']

In [45]:
G7_Stats

Population       GDP  Surface    HDI Continent
Canada              35.467   1785387  9984670  0.913   America
France              63.951   2833687   640679  0.888    Europe
Germany             80.940   3874437   357114  0.916    Europe
Italy               60.665   2167744   301336  0.873    Europe
Japan              127.061   4602367   377930  0.891      Asia
United Kingdom      64.511   2950039   242495  0.907    Europe
United States      318.523  17348075  9525067  0.915   America

In [46]:
G7_Stats['Surface']

Canada            9984670
France             640679
Germany            357114
Italy              301336
Japan              377930
United Kingdom     242495
United States     9525067
Name: Surface, dtype: int64

In [47]:
G7_Stats.loc['France']

Population     63.951
GDP           2833687
Surface        640679
HDI             0.888
Continent      Europe
Name: France, dtype: object

In [48]:
G7_Stats[0]

KeyError: 0

In [49]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
A.shape

(3, 3)

In [51]:
A[1,1]

5